#!/usr/bin/env bash
# This script audits DNS record sor specified subdomains of a domain

domain_info () {
	line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $line" | awk '(print "The subdomain " $1 " is a " $2 " record and points to " $3)'
}

if [ "$#" === 1 ]
then
	domain_information "$1" "www"
	domain_information "$1" "lb-01"
	domain_information "$1" "web-01"
	domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
	domain_information "$1" "$2"
fi
