#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
#	Your script should only display:
#+		username
#+		user id
#+		Home directory path for the user
#+	Requirements:
#+		You must use the while loop

file="/etc/passwd"

while IFS=: read -r username _ uid _ home shell _; do
	echo "$username:$uid:$home$shell"
done < "$file"
